export const POSITIONS = [
  'Software Engineer',
  'Front-end Developer',
  'Back-end Developer',
  'Full-stack Developer',
  'Mobile Developer',
  'Game Developer',
  'DevOps Engineer',
  'Data Engineer',
  'Data Scientist',
  'AI Engineer',
  'Cybersecurity Engineer',
  'Network Engineer',
  'Database Administrator',
  'System Administrator',
  'QA Engineer',
  'Blockchain Developer',
  'AR/VR Developer',
  'Tech Lead',
  'Software Architect',
  'Project Manager',
  'Product Manager',
  'Scrum Master',
  'Business Analyst',
  'UI/UX Designer',
  'Graphic Designer',
  'Technical Writer',
  'HR Manager',
  'Sales Manager',
  'Marketing Manager',
  'SEO Specialist',
  'SMM Manager',
  'Affiliate Manager',
  'Account Manager',
  'Legal Counsel',
  'Finance Manager'
]

export const SKILLS = [
  'Python',
  'Java',
  'JavaScript',
  'TypeScript',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Swift',
  'Kotlin',
  'React',
  'Angular',
  'Vue.js',
  'Django',
  'Flask',
  'Spring',
  'Laravel',
  'Flutter',
  'React Native',
  'SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'NoSQL',
  'Redis',
  'Oracle Database',
  'Git',
  'GitHub',
  'GitLab',
  'TensorFlow',
  'PyTorch',
  'OpenCV',
  'Tableau',
  'Power BI',
  'Figma',
  'Adobe XD',
  'Sketch',
  'Agile',
  'Scrum',
  'Kanban',
  'JIRA',
  'Confluence',
  'BPMN',
  'UML',
  'AWS',
  'Google Cloud',
  'Microsoft Azure',
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Jenkins',
  'Prometheus',
  'Grafana',
  'REST',
  'GraphQL',
  'Postman',
  'Swagger',
  'Selenium',
  'JUnit',
  'TestNG',
  'TestRail',
  'Zephyr',
  'Cypress',
  'TCP/IP',
  'DNS',
  'HTTP/HTTPS',
  'VPN',
  'Unity',
  'Unreal Engine',
  'WebXR',
  'VMware',
  'Hyper-V',
  'Solidity',
  'Functional testing',
  'Manual testing',
  'UI/UX testing',
  'CSS',
  'Chrome DevTools',
  'HTTP(S)',
  'HTML',
  'JSON',
  'Quality Assurance',
  'API testing',
  'Test cases',
  'Web testing',
  'Mobile testing',
  'Cross-browser testing',
  'Android/IOS',
  'Test documentation',
  'Bug reporting',
  'SDLC/STLC',
  'Charles Proxy',
  'Locker',
  'Lucidchart',
  'Trello',
  'Miro',
  'Waterfall',
  'SDLC',
  'Brainstorming',
  'Use Case Diagrams',
  'Decomposition',
  'Documentation of requirements'
]

export const SECTOR = [
  'EdTech',
  'FinTech',
  'HealthTech',
  'E-commerce',
  'TravelTech',
  'HR Tech',
  'Gaming'
]
